### ISSUE TITLE
Как сделать одинаковое время trx и zip файлов после сборки?

### ISSUE THREAD

**Issue by SharkyEXE** [alex2844/padavan-builder#1]
Здравствуйте

После сборки прошивки - создался файл с расширением trx, файл с расширением trx упакован в файл с расширением zip

В файле pre-build.sh такой код
```
ln -snf /usr/share/zoneinfo/Africa/Nairobi /etc/localtime
apt update
DEBIAN_FRONTEND=noninteractive apt install tzdata -y
date
```

![2024-11-04_0002](https://github.com/user-attachments/assets/d35c3bc2-4ed3-4099-81b5-0d22e37e4843)

Но время файла с расширением trx - всемирное время (UTC)

Current default time zone: 'Africa/Nairobi'
Local time is now:      Sun Nov  3 23:43:19 EAT 2024.
Universal Time is now:  Sun Nov  3 20:43:19 UTC 2024.

File: padavan-ng/trunk/images/RT-N56UB1_3.4.3.9L-102-543451d5a6.trx
  Size: 14532570  	Blocks: 28384      IO Block: 4096   regular file
Device: 801h/2049d	Inode: 698913      Links: 1
Access: (0644/-rw-r--r--)  Uid: (    0/    root)   Gid: (    0/    root)
Access: 2024-11-04 00:20:50.351683705 +0300
Modify: 2024-11-04 00:20:50.211682600 +0300
Change: 2024-11-04 00:20:50.211682600 +0300
 Birth: 2024-11-04 00:20:50.143682064 +0300

Скриншот - я скачал zip-файл и открываю zip-файл на Windows 11 в программе 7-Zip версии 23.01 (x64)

![2024-11-04_0001](https://github.com/user-attachments/assets/ff6f6803-dac2-4ed7-88d8-b87e0faa980d)

Можно или нельзя сделать так, чтобы время файла с расширением trx внутри zip-архиве будет такое же, как имя файла zip-архива?

Для примера
время создания zip файла 00.20.50
время файла с расширением trx внутри zip-архива также 00:20

Спасибо!

**Comment by alex2844** [comment]
Добрый день.

судя по имени артефакта - будто не мой код используется, т.к. артефакты упаковываются с таким именем
```bash
${{ env.CONFIG_VENDOR }}_${{ env.FW_NAME }} # XIAOMI_MI-4A_100M_3.4.3.9L-102-98917151b
```

если я вас правильно понял, то вы хотите чтоб в имени артефакта (zip) был другой часовой пояс,
то я бы попробовал так
```bash
TZ="Africa/Nairobi" date "+%Y.%m.%d_%H.%M.%S"
```
либо
```bash
TZ="Africa/Nairobi" date -d "$(stat -c %x ${FW_FILE_NAME})" "+%Y.%m.%d_%H.%M.%S"
```

**Comment by SharkyEXE** [comment]
Здравствуйте.

За "в имени артефакта (zip) был другой часовой пояс" - спасибо.
![382670485-ff6f6803-dac2-4ed7-88d8-b87e0faa980d](https://github.com/user-attachments/assets/f8fff721-d695-458b-8b89-6109075d5cd1)

Но задумка - чтобы файлы внутри артефакта (zip) имели же точно такую дату и время, как и "в имени артефакта (zip) был другой часовой пояс"

**Comment by alex2844** [comment]
если вы хотите не имя артефакта изменить, а дату создания файла - то в метаданных файла файловая система хранит временные метки (timestamp), а не отформатированную строку
тем самым если я со своего репозитория скачаю артефакт и открою у себя, то даты будут в моем часовом поясе

<details>
  <summary>Github actions</summary>

  ![image](https://github.com/user-attachments/assets/f48d7b74-9d2d-4305-9fd2-38674e15f419)
</details>

<details>
  <summary>Файловый менеджер</summary>

  ![image](https://github.com/user-attachments/assets/14243a9f-b466-4765-9f60-2504de19f379)
</details>

**Comment by SharkyEXE** [comment]
Не обижайтесь, я пишу как есть, может я что делаю не так

1) у меня компьютер - Windows 11
2) установлена программа-архиватор 7-Zip версии 23.01 (x64)

После сборки прошивки - создался файл с расширением trx, файл с расширением trx упакован в файл с расширением zip

![382841419-d35c3bc2-4ed3-4099-81b5-0d22e37e4843](https://github.com/user-attachments/assets/3e834a90-da34-45cf-9a1c-abb5e02c576b)

Скриншот - я скачал zip-файл и открываю zip-файл на Windows 11 в программе 7-Zip версии 23.01 (x64)

![382670485-ff6f6803-dac2-4ed7-88d8-b87e0faa980d](https://github.com/user-attachments/assets/32167023-99f3-4cde-afbf-63dff09f3da9)

- хочется время создания zip файла (ДОписка в названии файла) 00.20.50
- время файла с расширением trx внутри zip-архива также 00:20

**Comment by alex2844** [comment]
Я не пользуюсь виндой и тем самым виндовым софтом по типу 7zip, но если вы хотите чтоб 7zip не конвертировало время в локальное время, то это нужно писать разработчикам 7zip

**Comment by SharkyEXE** [comment]
Я особо не понимаю, не знаток.
1) Это 7zip (сама по себе) программа может удалять - 3 часа из времени файла внутри архива чтоли?
2) Еще - у Вас сейчас время 13-00, например, по Москве, (zip) архив создастся (build зеленый) в 13-00 - Вы откроете zip архив - у Вас 13-00 время для trx файла будет?
3) По моей идее, толковой или нет - какая дата и время trx файла была, с такой датой и временем zip архив создался
4) Еще может быть версия - время trx файла верное, но скрипт (упаковка в zip) эту дату использует как UTC +00:00 или как это нормально называется, но это домыслы, догадки, я не знаю.

**Comment by alex2844** [comment]
Да
В этом сообщении показывал https://github.com/alex2844/padavan-builder/issues/1#issuecomment-2463952879
По моему часовому времени в 6 утра ровно запускается сборка прошивки, и дата изменения файла .trx 6 утра 14 минут

**Comment by SharkyEXE** [comment]
Я не великий знаток, тогда и WinRAR 6.24 64 разрядный не так показывает чтоли?
![WinRAR 6 24 64 разрядная](https://github.com/user-attachments/assets/597ae6b4-df00-4d41-a0a8-d7f552266dd6)

Ладно 7zip не так внутри время trx показывается, то две программы - это уже беда...

Пожалуйста, Вы можете в название zip у Вас добавить

`${{ env.CONFIG_VENDOR }}_${{ env.FW_NAME }} # XIAOMI_MI-4A_100M_3.4.3.9L-102-98917151b`

`TZ="Africa/Nairobi" date "+%Y.%m.%d_%H.%M.%S"`

либо

`TZ="Africa/Nairobi" date -d "$(stat -c %x ${FW_FILE_NAME})" "+%Y.%m.%d_%H.%M.%S"`

У Вас на выходе получится zip архив с названием XIAOMI_MI-4A_100M_3.4.3.9L-102-98917151b_2024-11-08_14-00-00.zip

А вот внутри - trx файл время будет или нет 14-00?

Я сам вечером 08.11.2024 проверю

`${{ env.CONFIG_VENDOR }}_${{ env.FW_NAME }} # XIAOMI_MI-4A_100M_3.4.3.9L-102-98917151b`

`TZ="Africa/Nairobi" date "+%Y.%m.%d_%H.%M.%S"`

либо

`TZ="Africa/Nairobi" date -d "$(stat -c %x ${FW_FILE_NAME})" "+%Y.%m.%d_%H.%M.%S"`

Всё-же ну не может две программы 7zip и WinRAR неверное, точнее не корректное или как правильно называется время trx файла отображать, хотя возможно многое...

**Comment by alex2844** [comment]
Раз у вас несколько приложений не верно конвертируют время, то предположу что дело всетаки в винде.
Как писал ранее - я виндой не пользуюсь, загуглил - проверьте чтоб в настройках времени стояли галочки с автоматическим определением времени и нажмите на синхронизировать время

**Comment by SharkyEXE** [comment]
Спасибо Вам, я сам вечером 08.11.2024 проверю

${{ env.CONFIG_VENDOR }}_${{ env.FW_NAME }} # XIAOMI_MI-4A_100M_3.4.3.9L-102-98917151b

TZ="Africa/Nairobi" date "+%Y.%m.%d_%H.%M.%S"

либо

TZ="Africa/Nairobi" date -d "$(stat -c %x ${FW_FILE_NAME})" "+%Y.%m.%d_%H.%M.%S"

И настройки Windows 11 "в настройках времени стояли галочки с автоматическим определением времени + синхронизировать время"

**Comment by SharkyEXE** [comment]
Прошу прощения

1) В файле https://github.com/SharkyEXE/padavan-builder/blob/main/.github/workflows/build.yml правлю

БЫЛО

name: ${{ env.CONFIG_VENDOR }}_${{ env.FW_NAME }}

СТАЛО

`name: ${{ env.CONFIG_VENDOR }}_${{ env.FW_NAME }} TZ="Africa/Nairobi" date "+%Y.%m.%d_%H.%M.%S"`

Не сработало

![2024-11-9 11-7-18](https://github.com/user-attachments/assets/12015c36-4678-491f-8ee2-2fd8236d2ce2)

Пожалуйста, помогите.

PS. В Windows 11 часовой пояс так

![Снимок экрана 2024-11-08 214327](https://github.com/user-attachments/assets/442f5084-5d81-45b3-af7f-e046a1eb42c9)

**Comment by alex2844** [comment]
по ссылке 404 ошибка
либо не верную ссылку скидываете, либо репозиторий у вас закрыт

после 20ой строки https://github.com/alex2844/padavan-builder/blob/main/.github/workflows/build.yml#L20
echo "DATE=$(TZ='Africa/Nairobi' date '+%Y.%m.%d_%H.%M.%S')" >> $GITHUB_ENV

вместо https://github.com/alex2844/padavan-builder/blob/main/.github/workflows/build.yml#L27
name: ${{ env.CONFIG_VENDOR }}_${{ env.FW_NAME }}
будет
name: ${{ env.CONFIG_VENDOR }}_${{ env.FW_NAME }}_${{ env.DATE }}

**Comment by SharkyEXE** [comment]
Здравствуйте

1) Прошу прощения, репозиторий был ЗАкрыт, теперь открыл

https://github.com/SharkyEXE/padavan-builder-workflow/blob/main/.github/workflows/build.yml

2) Сделал правки по Вашему совету, собираю прошивку...

![Снимок экрана 2024-11-09 175458](https://github.com/user-attachments/assets/74766eb6-80dd-4917-b706-ec410c1f3de2)

**Comment by SharkyEXE** [comment]
Здравствуйте.

С Вашим советом - дата и время в названии файла появилось, супер, класс

![Снимок экрана 2024-11-09 190544](https://github.com/user-attachments/assets/4d8cc9f0-4777-4649-a1ff-30f2679ccab6)

[ASUSRT-N56UB1_3.4.3.9L-102-a10c37eef_2024.11.09_15.42.42.zip](https://github.com/user-attachments/files/17688538/ASUSRT-N56UB1_3.4.3.9L-102-a10c37eef_2024.11.09_15.42.42.zip)

Пожалуйста, последний штрих - как сделать:
1) время в названии файла +3 часа
было время в названии файла 15.42.42, а хочется +3 часа - то есть 18.42.42
2) время trx файла +3 часа
было время trx файла 15.42, а хочется +3 часа - то есть 18.42

**Comment by alex2844** [comment]
Не совсем понимаю почему вы в этот проект пишете, раз по ссылке выше - у Вас форк чужого проекта
Так же я не являюсь разработчиком, не пользователем винды и виндового софта что у вас на скриншоте
